version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parking-db
    environment:
      POSTGRES_DB: parkingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: parking-service
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/parkingdb
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data: